#8: Houston, we have a problem
DmitriyTeterin/horsesharing pull request #11
Opened 2021-12-08 14:23 UTC by DmitriyTeterin

2021-12-08 15:01 UTC, mbyakow requested changes

2021-12-08 15:01 UTC, mbyakow commented on index.php
> +    return $filteredHorse;
Не хватает пустой строки перед `return`.

2021-12-14 03:39 UTC, DmitriyTeterin commented on index.php
> +/**
исправил

2021-12-14 03:39 UTC, DmitriyTeterin commented on index.php
> +$newFilteredHorse = filter($horses, 2, 3);
исправил

2021-12-14 03:40 UTC, DmitriyTeterin commented on index.php
> +    return $filteredHorse;
исправил

2021-12-15 07:24 UTC, mbyakow commented on index.php
> +    ['id' => 1,
Не исправлено

2021-12-15 07:25 UTC, mbyakow commented on index.php
> +/**
Описание не соответствует кейсам, в которых может быть применена функция.

2021-12-15 07:26 UTC, mbyakow commented on index.php
> + * Фильтрует список лошадей по городу или по тарифу.
Описание не соответствует кейсам, в которых может быть применена функция.

2021-12-15 07:26 UTC, mbyakow commented on index.php
> +$filteredHorseByCity = filter($filteredHorseByTariff, 'city', 2);
Обе строки можно упростить до
`$hore = ...`

2021-12-15 07:27 UTC, mbyakow commented on index.php
> +//https://www.youtube.com/watch?v=4SCrZ6bEqAc
Посмотрел, оценил, но нужно будет подчистить :)

2021-12-15 14:40 UTC, DmitriyTeterin commented on index.php
> + * Фильтрует список лошадей по городу или по тарифу.
исправил на 
* Фильтрует список лошадей по заданному параметру.

2021-12-15 14:41 UTC, DmitriyTeterin commented on index.php
> +/**
исправил на
* Ищет в справочниках значение параметра лошади по id.

2021-12-15 14:45 UTC, DmitriyTeterin commented on index.php
> +$filteredHorseByCity = filter($filteredHorseByTariff, 'city', 2);
в защиту своих наименований могу сказать, что так мне более понятно . это же не критичная правка?

2021-12-15 14:46 UTC, DmitriyTeterin commented on index.php
> +//https://www.youtube.com/watch?v=4SCrZ6bEqAc
)))))0)

2021-12-15 14:47 UTC, DmitriyTeterin commented on index.php
> +    ['id' => 1,
исправил

2021-12-15 16:09 UTC, mbyakow commented on index.php
> +$filteredHorseByCity = filter($filteredHorseByTariff, 'city', 2);
Если придерживаться такой стратегии, тогда:
1. Название `$filteredHorseByCity` некорректно, т.к. это список отфильтрованных по тарифу (ранее) и по городу. Получается `$filteredHorseByTariffAndCity`.
2. Что если у тебя будет 10 фильтров? Как будет называться (точнее, какой длины будет) последняя переменная?
3. С учётом п. 2, можешь ли ты с текущим названием запихать обработчик в цикл?

2021-12-15 16:10 UTC, mbyakow commented on index.php
> +$filteredHorseByCity = filter($filteredHorseByTariff, 'city', 2);
Ну и если совсем придираться, то должно быть `horses`, множественное число :о)

2021-12-15 16:10 UTC, mbyakow commented on index.php
> + * Фильтрует список лошадей по городу или по тарифу.
Этот и второй методы ты можешь применять толко для массива лошадей?

2021-12-16 13:58 UTC, merged