Feature/moving functions to files
DmitriyTeterin/horsesharing pull request #15
Opened 2022-01-27 14:23 UTC by DmitriyTeterin

Closed #14

2022-01-27 16:01 UTC, mbyakow requested changes
Кроме указанных замечаний есть одно общее: пляшет стиль кода. Отступы, переносы, слипшиеся конструкции, лишние пустые строки или наоборот отсутствующие для выделения логических блоков. Рекомендация: привыкать сразу писать правильно, а также настроить и использовать автоформатирование.

2022-02-14 12:15 UTC, DmitriyTeterin commented on functionFindByItem.php
> +
честно я даже не помню. по сути тут нафиг не надо пустую строку. удалю.

2022-02-14 12:16 UTC, DmitriyTeterin commented on index.php
> +foreach($horses as $horse){
я понял, это типа автоформатирование кода в vscode. никакой функциональной нагрузки это изменение не несет.

2022-02-14 12:21 UTC, DmitriyTeterin commented on functionFilter.php
> +
втоформатирование кода в vscode

2022-02-14 12:25 UTC, DmitriyTeterin commented on database.php
> +    if (($file = fopen($path, "r")) !== FALSE) {
про нижний регистр false и true понял. просто увидел в примере и сделал как там. на будущее запомню. 
![image](https://user-images.githubusercontent.com/92454742/153864019-60141300-ed56-49dd-8309-7dc4a2326781.png)

2022-02-14 12:35 UTC, DmitriyTeterin commented on database.php
> +    if (($file = fopen($path, "r")) !== FALSE) {
**_Что будет, если я укажу не существующий файл, либо если при его чтении произойдёт ошибка?_**

произойдет ошибка и ничего не сработает.

2022-02-14 12:43 UTC, DmitriyTeterin commented on database.php
> +    if (($file = fopen($path, "r")) !== FALSE) {
// было
$a = true;
if ($a !== false) {
  // что-то читаем
}
// возвращаем ответ


// стало
$a = true;
if ($a === false) {
 // что-то пошло не так, заканчиваем выполнение 
}
// всё ок, читаем файл и выполняем действия дальше




не понял куда это применить

2022-02-14 13:09 UTC, DmitriyTeterin commented on database.php
> +                if(is_numeric($data[$c]) === TRUE){
переделал

2022-02-14 13:15 UTC, DmitriyTeterin commented on database.php
> +                   $item[$keys[$c]] = (int)$data[$c];
вынес

2022-02-14 13:15 UTC, DmitriyTeterin commented on database.php
> +function csvArray ($path): array {
указан

2022-02-14 13:16 UTC, DmitriyTeterin commented on database.php
> +    $array = explode("\n", file_get_contents($path, true, null, 0));
будет ошибка, код не сработает. Задай вопрос иначе как-то, я не пойму что ты от меня хочешь)

2022-02-14 13:16 UTC, DmitriyTeterin commented on database.php
> +        $keys = fgetcsv($file, 1000, ";");
Задай вопрос иначе как-то, я не пойму что ты от меня хочешь)

2022-02-14 13:33 UTC, DmitriyTeterin commented on database.php
> +    $cnt = count($keys);
` $arrayCount = count($array);
    $keysCount = count($keys);`

2022-02-14 13:40 UTC, DmitriyTeterin commented on database.php
> +        $result[$i-1] = $resultArr;
блин, ну да. ведь 1-1=0))))))

2022-02-14 13:41 UTC, DmitriyTeterin commented on database.php
> +                $resultArr[trim($keys[$n])] = (int)$res[$n];
исправил

2022-02-14 14:16 UTC, DmitriyTeterin commented on database.php
> +            if(is_numeric(trim($res[$n])) === TRUE){
сделал

2022-02-14 14:17 UTC, DmitriyTeterin commented on database.php
> +function csvFgets ($path): array{
указан

2022-02-14 15:26 UTC, DmitriyTeterin commented on database.php
> +function csvFread ($path): array{
готово

2022-02-16 12:21 UTC, mbyakow approved these changes

2022-02-16 12:22 UTC, merged